name: Publish package on new release

on:
  push
  # release:
  #   types: [published]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{secrets.PAT}}
      - run: |
          git config user.name sahil-shubham
          git config user.email sahil.shubham2000@gmail.com
          yarn version --patch
          git push
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
